### ISSUE TITLE
Sorting of elements trouble

### ISSUE THREAD

**Issue by KacperKotlewski** [mxkooo/JavaScriptGame#1]
As you said on DC in [this thread](https://discord.com/channels/814227146423402547/822033286150750219/998689704516010015)
You have trouble with sorting a data set,
after a discussion there I decided that it would be a good idea if I could cover the changes that I mentioned to help you with your trouble.
 If you would like to cover it by yourself it will be better for you but if you give me a green light I can cover it.

**Comment by mxkooo** [comment]
Green light 4 u:-)

**Comment by KacperKotlewski** [comment]
done
